<script setup lang="ts">
import type { Map } from 'ol'

import { LV95 } from '@swissgeo/coordinates'
import log from '@swissgeo/log'
import ScaleLine from 'ol/control/ScaleLine'
import { computed, inject, onBeforeUnmount, onMounted, useTemplateRef } from 'vue'

import usePositionStore from '@/store/modules/position'

const {
    scaleType = 'line',
    minWidth = 100,
    withRelativeSize = false,
} = defineProps<{
    scaleType?: 'line' | 'bar'
    minWidth?: number
    withRelativeSize?: boolean
}>()

const scaleLineElement = useTemplateRef<HTMLElement>('scaleLineElement')

const positionStore = usePositionStore()

const showScaleLine = computed<boolean>(
    () => positionStore.projection.epsg === LV95.epsg || positionStore.zoom >= 9
)

const scaleLine = new ScaleLine({
    className: `scale-${scaleType}`,
    bar: scaleType === 'bar',
    minWidth: minWidth,
})

const olMap = inject<Map>('olMap')
if (!olMap) {
    log.error('OpenLayersMap is not available')
    throw new Error('OpenLayersMap is not available')
}

onMounted(() => {
    if (scaleLineElement.value) {
        scaleLine.setTarget(scaleLineElement.value)
    }
    olMap.addControl(scaleLine)
})
onBeforeUnmount(() => olMap.removeControl(scaleLine))
</script>

<template>
    <!-- The initialization will fail with `v-if` if initial zoom is too low. -->
    <div
        v-show="showScaleLine"
        ref="scaleLineElement"
        class="scale-line-container"
        :class="{ 'with-relative-size': withRelativeSize }"
        data-cy="scaleline"
    />
</template>

<style lang="scss">
/* Must be unscoped, as the scaleLine is generated by OpenLayers on the fly */
@import '@swissgeo/theme/scss/geoadmin-theme';

.scale-line-container {
    .scale-line {
        &-inner {
            max-width: 100%;
            border: 2px solid $black;
            border-top: none;
            text-align: center;
            font-weight: bold;
            color: $black;
            background-color: rgba($white, 0.7);
        }
    }

    .scale-bar {
        $scaleBarBorderColor: $black;
        $scaleBarPrimary: $black;
        $scaleBarSecondary: $light-grey;

        $fontSize: 8px;

        .scale-bar-inner {
            display: flex;
        }

        &.with-relative-size {
            $fontSize: max(max(0.8vw, 0.8vh), 8px);
        }

        .ol-scale-step-marker {
            width: 1px;
            height: calc(2 * $fontSize);
            background-color: $scaleBarBorderColor;
            float: right;
            z-index: 10;
        }

        .ol-scale-step-text {
            position: absolute;
            bottom: calc(-1 * $fontSize);
            font-size: $fontSize;
            z-index: 11;
            color: $scaleBarBorderColor;
        }

        .ol-scale-text {
            position: absolute;
            font-size: $fontSize;
            text-align: center;
            bottom: calc(2 * $fontSize);
            color: $scaleBarBorderColor;
        }

        .ol-scale-singlebar {
            position: relative;
            height: $fontSize;
            z-index: 9;
            box-sizing: border-box;
            border: 1px solid $scaleBarBorderColor;
        }

        .ol-scale-singlebar-even {
            background-color: $scaleBarSecondary;
        }

        .ol-scale-singlebar-odd {
            background-color: $scaleBarPrimary;
        }

        & {
            position: relative;
        }
    }
}
</style>
