# .github/release.yml
# WARNING this file is managed by terraform and cannot be edited manually, see
# geoadmin/infra-terraform-bgdi/tf/github/geoadmin/modules/service-repository-semver/release_config.tf

changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
      - skip-rn
      - skip-release-note
      - no-release-note
      - no-rn
      - no-changelog
      - new-release
    authors:
      - terraform-bgdi
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Data Updates
      labels:
        - data
        - data-integration
    - title: Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: Other Changes
      labels:
        - "*"
