---
# .github/release.yml
# WARNING this file is managed by terraform and cannot be edited manually, see
# tf/github/geoadmin/modules/github-auto-release-notes-config/main.tf

changelog:
  exclude:
    labels:
      - skip-release-note
      - refactoring
      - new-release
    authors:
      - terraform-bgdi
  categories:
    - title: ":boom: Breaking Changes"
      labels:
        - breaking-change
    - title: ":sparkles: New Features"
      labels:
        - feature
    - title: ":card_index_dividers: Data Updates"
      labels:
        - data-integration
    - title: ":bug: Bug Fixes"
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
