packages:
    - packages/*
catalog:
    '@4tw/cypress-drag-drop': ^2.3.0
    '@cypress/vite-dev-server': ^6.0.3
    '@cypress/vue': ^6.0.2
    '@eslint/js': ^9.26.0
    '@eslint/markdown': ^6.4.0
    '@floating-ui/vue': ^1.1.6
    '@fontsource/noto-sans': ^5.2.7
    '@fortawesome/fontawesome-svg-core': ^6.7.2
    '@fortawesome/free-brands-svg-icons': ^6.7.2
    '@fortawesome/free-regular-svg-icons': ^6.7.2
    '@fortawesome/free-solid-svg-icons': ^6.7.2
    '@fortawesome/vue-fontawesome': ^3.0.8
    '@geoblocks/cesium-compass': ^0.6.0
    '@geoblocks/mapfishprint': ^0.2.20
    '@geoblocks/ol-maplibre-layer': ^1.0.3
    '@intlify/core-base': ^11.1.2
    '@intlify/unplugin-vue-i18n': ^6.0.3
    '@mapbox/togeojson': ^0.16.2
    '@nuintun/qrcode': ^5.0.2
    '@popperjs/core': ^2.11.8
    '@prettier/plugin-xml': ^3.4.1
    '@rushstack/eslint-patch': ^1.11.0
    '@tailwindcss/vite': ^4.1.11
    '@tsconfig/node22': ^22.0.1
    '@turf/turf': ^7.2.0
    '@types/geojson': ^7946.0.16
    '@types/jsdom': ^21.1.7
    '@types/lodash': ^4.17.16
    '@types/node': ^22.15.14
    '@types/openlayers': ^4.6.23
    '@types/proj4': ^2.5.6
    '@vitejs/plugin-basic-ssl': ^2.0.0
    '@vitejs/plugin-vue': ^5.2.3
    '@vite-pwa/assets-generator': ^1.0.0
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.5.0
    '@vue/tsconfig': ^0.7.0
    animate.css: ^4.1.1
    axios: ^1.9.0
    axios-retry: ^4.5.0
    bootstrap: ^5.3.6
    cesium: 1.119.0
    chai: ^5.2.0
    chart.js: ^4.4.9
    chartjs-plugin-zoom: ^2.2.0
    cypress: ^14.3.3
    cypress-browser-permissions: ^1.1.0
    cypress-real-events: ^1.14.0
    cypress-recurse: ^1.35.3
    cypress-vite: ^1.6.0
    cypress-wait-until: ^3.0.2
    dompurify: ^3.2.5
    dotenv: ^16.5.0
    eslint: ^9.26.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-cypress: ^4.3.0
    eslint-plugin-mocha: ^11.0.0
    eslint-plugin-perfectionist: ^4.12.3
    eslint-plugin-prettier: ^5.4.0
    eslint-plugin-vue: ^10.1.0
    form-data: ^4.0.2
    geographiclib-geodesic: ^2.1.1
    geotiff: ^2.1.3
    git-describe: ^4.1.1
    gitconfig: ^2.0.8
    globals: ^16.1.0
    googleapis: ^148.0.0
    hammerjs: ^2.0.8
    jquery: ^3.7.1
    jsdom: ^26.1.0
    jszip: ^3.10.1
    lodash: ^4.17.21
    maplibre-gl: ^5.5.0
    mime-types: ^3.0.1
    mocha-junit-reporter: ^2.2.1
    ol: ^10.6.0
    pako: ^2.1.0
    postcss-html: ^1.8.0
    prettier: ^3.5.3
    prettier-plugin-jsdoc: ^1.3.2
    prettier-plugin-packagejson: ^2.5.11
    prettier-plugin-tailwindcss: ^0.6.11
    print-js: ^1.6.0
    proj4: ^2.15.0
    reproject: ^1.2.7
    rimraf: ^6.0.1
    rollup: ^4.41.1
    sass: 1.77.7
    sharp: ^0.34.1
    sortablejs: ^1.15.6
    start-server-and-test: ^2.0.11
    stylelint: ^16.19.0
    stylelint-config-recommended-scss: ^14.1.0
    stylelint-config-recommended-vue: ^1.6.0
    stylelint-order: ^7.0.0
    stylelint-scss: ^6.11.1
    tailwindcss: ^4.1.5
    typescript: ^5.8.3
    typescript-eslint: ^8.32.0
    uuid: ^11.1.0
    vite-node: ^3.1.3
    vite-plugin-conditional-compiler: ^0.3.1
    vite-plugin-dts: ^4.5.3
    vite-plugin-pwa: ^1.0.0
    vite-plugin-static-copy: ^2.3.1
    vite-plugin-vue-devtools: ^7.7.6
    vite-tsconfig-paths: ^5.1.4
    vite: ^6.3.5
    vitest: ^3.1.3
    vue: ^3.5.13
    vue-chartjs: ^5.3.2
    vue-i18n: ^11.1.3
    vue-router: ^4.5.1
    vue-tsc: ^2.2.10
    vue3-social-sharing: ^1.4.1
    vuex: ^4.1.0
    workbox-cacheable-response: ^7.3.0
    workbox-core: ^7.3.0
    workbox-expiration: ^7.3.0
    workbox-precaching: ^7.3.0
    workbox-routing: ^7.3.0
    workbox-strategies: ^7.3.0
    workbox-window: ^7.3.0
    write-yaml-file: ^5.0.0
    yargs: ^17.7.2
