packages:
  - packages/*
catalog:
  "@4tw/cypress-drag-drop": ^2.3.0
  "@cypress/vite-dev-server": ^6.0.2
  "@cypress/vue": ^6.0.2
  "@eslint/markdown": ^6.2.2
  "@fontsource/noto-sans": ^5.1.1
  "@fortawesome/fontawesome-svg-core": ^6.7.2
  "@fortawesome/free-brands-svg-icons": ^6.7.2
  "@fortawesome/free-regular-svg-icons": ^6.7.2
  "@fortawesome/free-solid-svg-icons": ^6.7.2
  "@fortawesome/vue-fontawesome": ^3.0.8
  "@geoblocks/cesium-compass": ^0.5.4
  "@geoblocks/mapfishprint": ^0.2.19
  "@geoblocks/ol-maplibre-layer": ^1.0.3
  "@ivanv/vue-collapse-transition": ^1.0.2
  "@mapbox/togeojson": ^0.16.2
  "@nuintun/qrcode": ^4.1.13
  "@popperjs/core": ^2.11.8
  "@prettier/plugin-xml": ^3.4.1
  "@rushstack/eslint-patch": ^1.10.5
  "@turf/turf": ^7.2.0
  "@types/geojson": ^7946.0.16
  "@types/jsdom": ^21.1.7
  "@types/node": ^22.13.1
  "@types/proj4": ^2.5.6
  "@vitejs/plugin-basic-ssl": ^1.2.0
  "@vitejs/plugin-vue": ^5.2.1
  "@vue/tsconfig": ^0.7.0
  "@vue/eslint-config-prettier": "^10.2.0"
  animate.css: ^4.1.1
  axios: ^1.7.9
  axios-retry: ^4.5.0
  bootstrap: ^5.3.3
  cesium: 1.119.0
  chai: ^5.1.2
  chart.js: ^4.4.7
  chartjs-plugin-zoom: ^2.2.0
  cypress-browser-permissions: ^1.1.0
  cypress-real-events: ^1.14.0
  cypress-recurse: ^1.35.3
  cypress-vite: ^1.6.0
  cypress-wait-until: ^3.0.2
  cypress: ^14.0.3
  dompurify: ^3.2.4
  dotenv: ^16.4.7
  eslint: ^9.19.0
  eslint-plugin-cypress: ^4.1.0
  eslint-plugin-mocha: ^10.5.0
  eslint-plugin-perfectionist: ^4.8.0
  eslint-config-prettier: "^10.0.1"
  eslint-plugin-prettier: "^5.2.3"
  file-saver: ^2.0.5
  form-data: ^4.0.1
  geographiclib-geodesic: ^2.1.1
  geotiff: ^2.1.3
  git-describe: ^4.1.1
  gitconfig: ^2.0.8
  globals: ^15.14.0
  googleapis: ^144.0.0
  hammerjs: ^2.0.8
  jquery: ^3.7.1
  jsdom: ^26.0.0
  jszip: ^3.10.1
  lodash: ^4.17.21
  maplibre-gl: ^5.1.0
  mime-types: ^2.1.35
  mocha-junit-reporter: ^2.2.1
  ol: ^10.4.0
  pako: ^2.1.0
  prettier: ^3.4.2
  prettier-plugin-jsdoc: ^1.3.2
  print-js: ^1.6.0
  proj4: ^2.15.0
  reproject: ^1.2.7
  rimraf: ^6.0.1
  sass: 1.77.6
  sharp: ^0.33.5
  sortablejs: ^1.15.6
  start-server-and-test: ^2.0.10
  tippy.js: ^6.3.7
  typescript: ^5.7.3
  typescript-eslint: ^8.23.0
  vite-node: ^3.0.5
  vite-plugin-dts: ^4.5.0
  vite-plugin-static-copy: ^2.2.0
  vitest: ^3.0.4
  vue: ^3.5.13
  vue-chartjs: ^5.3.2
  vue-i18n: ^11.1.0
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
  vue3-social-sharing: ^1.3.1
  vuex: ^4.1.0
  write-yaml-file: ^5.0.0
  yargs: ^17.7.2
  vite: "^6.0.11"
