packages:
    - packages/*
catalog:
    '@4tw/cypress-drag-drop': ^2.3.1
    '@cypress/vite-dev-server': ^7.2.0
    '@cypress/vue': ^6.0.2
    '@eslint/js': 10.0.1
    '@eslint/markdown': ^7.5.1
    '@floating-ui/vue': ^1.1.10
    '@fontsource/noto-sans': ^5.2.10
    '@fortawesome/fontawesome-svg-core': ^7.2.0
    '@fortawesome/free-brands-svg-icons': ^7.2.0
    '@fortawesome/free-regular-svg-icons': ^7.2.0
    '@fortawesome/free-solid-svg-icons': ^7.2.0
    '@fortawesome/vue-fontawesome': ^3.1.3
    '@geoblocks/cesium-compass': ^0.6.0
    '@geoblocks/mapfishprint': ^0.3.0
    '@geoblocks/ol-maplibre-layer': ^1.0.3
    '@intlify/core-base': ^11.2.8
    '@intlify/unplugin-vue-i18n': ^11.0.7
    '@mapbox/togeojson': ^0.16.2
    '@microsoft/api-extractor': ^7.57.3
    '@nuintun/qrcode': ^5.0.3
    '@popperjs/core': ^2.11.8
    '@prettier/plugin-xml': ^3.4.2
    '@rushstack/eslint-patch': ^1.16.1
    '@tailwindcss/vite': ^4.2.0
    '@tmcw/togeojson': ^7.1.2
    '@tsconfig/node22': ^22.0.5
    '@turf/turf': ^7.3.4
    '@types/bootstrap': ^5.2.10
    '@types/chai': ^5.2.3
    '@types/geojson': ^7946.0.16
    '@types/jsdom': ^27.0.0
    '@types/lodash': ^4.17.24
    '@types/luxon': ^3.7.1
    '@types/node': ^25.3.0
    '@types/openlayers': ^4.6.23
    '@types/pako': ^2.0.4
    '@types/proj4': ^2.19.0
    '@vite-pwa/assets-generator': ^1.0.2
    '@vitejs/plugin-basic-ssl': ^2.1.4
    '@vitejs/plugin-vue': ^6.0.4
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.7.0
    '@vue/language-core': ^3.2.5
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^14.2.1
    '@xmldom/xmldom': ^0.8.11
    animate.css: ^4.1.1
    axios: ^1.13.5
    axios-retry: ^4.5.0
    bootstrap: ^5.3.8
    cesium: ^1.138.0
    chai: ^6.2.2
    chart.js: ^4.5.1
    chartjs-plugin-zoom: ^2.2.0
    cypress: ^15.10.0
    cypress-browser-permissions: ^1.1.0
    cypress-real-events: ^1.15.0
    cypress-recurse: ^1.37.1
    cypress-vite: ^1.8.0
    cypress-wait-until: ^3.0.2
    dompurify: ^3.3.1
    dotenv: ^17.3.1
    eslint: maintenance
    eslint-config-prettier: release-v9
    eslint-plugin-chai-friendly: ^1.1.0
    eslint-plugin-cypress: 5.3.0
    eslint-plugin-mocha: ^11.2.0
    eslint-plugin-perfectionist: ^5.6.0
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-vue: ^10.8.0
    form-data: ^4.0.5
    geographiclib-geodesic: ^2.2.0
    geotiff: ^3.0.3
    git-describe: ^4.1.1
    gitconfig: ^2.0.8
    globals: ^17.3.0
    googleapis: ^171.4.0
    hammerjs: ^2.0.8
    jquery: ^4.0.0
    jsdom: ^28.1.0
    jszip: ^3.10.1
    lodash: ^4.17.23
    luxon: ^3.7.2
    maplibre-gl: ^5.19.0
    mime-types: ^3.0.2
    mocha-junit-reporter: ^2.2.1
    ol: ^10.8.0
    pako: ^2.1.0
    pinia: ^3.0.4
    pinia-logger: ^1.3.14
    postcss-html: ^1.8.1
    prettier: ^3.8.1
    prettier-plugin-jsdoc: ^1.8.0
    prettier-plugin-packagejson: ^3.0.0
    prettier-plugin-tailwindcss: ^0.7.2
    print-js: ^1.6.0
    proj4: ^2.20.2
    reproject: ^1.2.7
    rimraf: ^6.1.3
    rollup: ^4.59.0
    sass: 1.77.7
    sharp: ^0.34.5
    sortablejs: ^1.15.7
    start-server-and-test: ^2.1.3
    stylelint: ^17.3.0
    stylelint-config-recommended-scss: ^17.0.0
    stylelint-config-recommended-vue: ^1.6.1
    stylelint-order: ^7.0.1
    stylelint-scss: ^7.0.0
    tailwindcss: ^4.2.0
    typescript: ^5.9.3
    typescript-eslint: ^8.56.0
    unplugin-dts: 1.0.0-beta.6
    uuid: ^13.0.0
    vite: ^7.3.1
    vite-node: ^5.3.0
    vite-plugin-conditional-compiler: ^0.4.0
    vite-plugin-dts: ^4.5.4
    vite-plugin-pwa: ^1.2.0
    vite-plugin-static-copy: ^3.2.0
    vite-plugin-vue-devtools: ^8.0.6
    vite-tsconfig-paths: ^6.1.1
    vitest: ^4.0.18
    vue: ^3.5.28
    vue-chartjs: ^5.3.3
    vue-i18n: ^11.2.8
    vue-router: ^5.0.3
    vue-tsc: ^3.2.5
    vue3-social-sharing: ^1.4.1
    vuex: ^4.1.0
    workbox-cacheable-response: ^7.4.0
    workbox-core: ^7.4.0
    workbox-expiration: ^7.4.0
    workbox-precaching: ^7.4.0
    workbox-routing: ^7.4.0
    workbox-strategies: ^7.4.0
    workbox-window: ^7.4.0
    write-yaml-file: ^5.0.0
    yaml: ^2.8.2
    yargs: ^18.0.0
