packages:
    - packages/*
catalog:
    '@4tw/cypress-drag-drop': ^2.3.0
    '@cypress/vite-dev-server': ^6.0.2
    '@cypress/vue': ^6.0.2
    '@eslint/js': ^9.22.0
    '@eslint/markdown': ^6.3.0
    '@fontsource/noto-sans': ^5.2.5
    '@fortawesome/fontawesome-svg-core': ^6.7.2
    '@fortawesome/free-brands-svg-icons': ^6.7.2
    '@fortawesome/free-regular-svg-icons': ^6.7.2
    '@fortawesome/free-solid-svg-icons': ^6.7.2
    '@fortawesome/vue-fontawesome': ^3.0.8
    '@geoblocks/cesium-compass': ^0.6.0
    '@geoblocks/mapfishprint': ^0.2.19
    '@geoblocks/ol-maplibre-layer': ^1.0.3
    '@ivanv/vue-collapse-transition': ^1.0.2
    '@mapbox/togeojson': ^0.16.2
    '@nuintun/qrcode': ^4.1.14
    '@popperjs/core': ^2.11.8
    '@prettier/plugin-xml': ^3.4.1
    '@rushstack/eslint-patch': ^1.11.0
    '@turf/turf': ^7.2.0
    '@types/geojson': ^7946.0.16
    '@types/jsdom': ^21.1.7
    '@types/node': ^22.13.10
    '@types/proj4': ^2.5.6
    '@vitejs/plugin-basic-ssl': ^2.0.0
    '@vitejs/plugin-vue': ^5.2.1
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.5.0
    '@vue/tsconfig': ^0.7.0
    '@floating-ui/vue': '^1.1.6'
    animate.css: ^4.1.1
    axios: ^1.8.3
    axios-retry: ^4.5.0
    bootstrap: ^5.3.3
    cesium: 1.119.0
    chai: ^5.2.0
    chart.js: ^4.4.8
    chartjs-plugin-zoom: ^2.2.0
    cypress: ^14.2.0
    cypress-browser-permissions: ^1.1.0
    cypress-real-events: ^1.14.0
    cypress-recurse: ^1.35.3
    cypress-vite: ^1.6.0
    cypress-wait-until: ^3.0.2
    dompurify: ^3.2.4
    dotenv: ^16.4.7
    eslint: ^9.22.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-cypress: ^4.2.0
    eslint-plugin-mocha: ^10.5.0
    eslint-plugin-perfectionist: ^4.10.1
    eslint-plugin-prettier: ^5.2.3
    eslint-plugin-vue: ^10.0.0
    file-saver: ^2.0.5
    form-data: ^4.0.2
    geographiclib-geodesic: ^2.1.1
    geotiff: ^2.1.3
    git-describe: ^4.1.1
    gitconfig: ^2.0.8
    globals: ^16.0.0
    googleapis: ^146.0.0
    hammerjs: ^2.0.8
    jquery: ^3.7.1
    jsdom: ^26.0.0
    jszip: ^3.10.1
    lodash: ^4.17.21
    maplibre-gl: ^5.2.0
    mime-types: ^2.1.35
    mocha-junit-reporter: ^2.2.1
    ol: ^10.4.0
    pako: ^2.1.0
    prettier: ^3.5.3
    prettier-plugin-jsdoc: ^1.3.2
    prettier-plugin-packagejson: ^v2.5.10
    print-js: ^1.6.0
    proj4: ^2.15.0
    reproject: ^1.2.7
    rimraf: ^6.0.1
    sass: 1.77.6
    sharp: ^0.33.5
    sortablejs: ^1.15.6
    start-server-and-test: ^2.0.11
    typescript: ^5.8.2
    typescript-eslint: ^8.26.1
    vite-node: ^3.0.8
    vite-plugin-dts: ^4.5.3
    vite-plugin-static-copy: ^2.3.0
    vite-plugin-vue-devtools: ^7.7.2
    vite: ^6.2.1
    vitest: ^3.0.8
    vue: ^3.5.13
    vue-chartjs: ^5.3.2
    vue-i18n: ^11.1.2
    vue-router: ^4.5.0
    vue-tsc: ^2.2.8
    vue3-social-sharing: ^1.3.1
    vuex: ^4.1.0
    write-yaml-file: ^5.0.0
    yargs: ^17.7.2
