packages:
    - packages/*
    - packages/config/*

catalog:
    '@4tw/cypress-drag-drop': ^2.3.1
    '@cypress/vite-dev-server': ^7.0.0
    '@cypress/vue': ^6.0.2
    '@eslint/js': ^9.38.0
    '@eslint/markdown': ^7.4.0
    '@floating-ui/vue': ^1.1.9
    '@fontsource/noto-sans': ^5.2.10
    '@fortawesome/fontawesome-svg-core': ^7.1.0
    '@fortawesome/free-brands-svg-icons': ^7.1.0
    '@fortawesome/free-regular-svg-icons': ^7.1.0
    '@fortawesome/free-solid-svg-icons': ^7.1.0
    '@fortawesome/vue-fontawesome': ^3.1.2
    '@geoblocks/cesium-compass': ^0.6.0
    '@geoblocks/mapfishprint': ^0.2.22
    '@geoblocks/ol-maplibre-layer': ^1.0.3
    '@intlify/core-base': ^11.1.12
    '@intlify/unplugin-vue-i18n': ^11.0.1
    '@mapbox/togeojson': ^0.16.2
    '@microsoft/api-extractor': ^7.53.1
    '@nuintun/qrcode': ^5.0.2
    '@pinia/testing': ^1.0.2
    '@popperjs/core': ^2.11.8
    '@prettier/plugin-xml': ^3.4.2
    '@rushstack/eslint-patch': ^1.14.0
    '@tailwindcss/vite': ^4.1.14
    '@tmcw/togeojson': ^7.1.2
    '@tsconfig/node22': ^22.0.2
    '@turf/turf': ^7.2.0
    '@types/bootstrap': ^5.2.10
    '@types/chai': ^5.2.2
    '@types/geojson': ^7946.0.16
    '@types/jsdom': ^27.0.0
    '@types/lodash': ^4.17.20
    '@types/luxon': ^3.7.1
    '@types/node': ^24.8.1
    '@types/openlayers': ^4.6.23
    '@types/pako': ^2.0.4
    '@types/sortablejs': ^1.15.9
    '@types/yargs': ^17.0.34
    '@typescript-eslint/utils': ^8.46.1
    '@vite-pwa/assets-generator': ^1.0.2
    '@vitejs/plugin-basic-ssl': ^2.1.0
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.6.0
    '@vue/language-core': ^3.1.1
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^13.9.0
    '@xmldom/xmldom': ^0.8.11
    animate.css: ^4.1.1
    axios: ^1.12.2
    axios-retry: ^4.5.0
    bootstrap: ^5.3.8
    cesium: ^1.134.1
    chai: ^6.2.0
    chart.js: ^4.5.1
    chartjs-plugin-zoom: ^2.2.0
    cypress: ^15.5.0
    cypress-browser-permissions: ^1.1.0
    cypress-real-events: ^1.15.0
    cypress-recurse: ^1.37.1
    cypress-vite: ^1.8.0
    cypress-wait-until: ^3.0.2
    dompurify: ^3.3.0
    dotenv: ^17.2.3
    eslint: ^9.38.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-chai-friendly: ^1.1.0
    eslint-plugin-cypress: ^5.2.0
    eslint-plugin-mocha: ^11.2.0
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-vue: ^10.5.1
    form-data: ^4.0.4
    geographiclib-geodesic: ^2.2.0
    geotiff: ^2.1.4-beta.0
    git-describe: ^4.1.1
    gitconfig: ^2.0.8
    globals: ^16.4.0
    googleapis: ^164.0.0
    hammerjs: ^2.0.8
    jquery: ^3.7.1
    jsdom: ^27.0.1
    jszip: ^3.10.1
    lodash: ^4.17.21
    luxon: ^3.7.2
    maplibre-gl: ^5.9.0
    mime-types: ^3.0.1
    mocha-junit-reporter: ^2.2.1
    ol: ^10.6.1
    pako: ^2.1.0
    pinia: ^3.0.3
    pinia-logger: ^1.3.14
    postcss-html: ^1.8.0
    prettier: ^3.6.2
    prettier-plugin-jsdoc: ^1.3.3
    prettier-plugin-packagejson: ^2.5.19
    prettier-plugin-tailwindcss: ^0.7.1
    print-js: ^1.6.0
    proj4: ^2.19.10
    reproject: ^1.2.7
    rimraf: ^6.0.1
    rollup: ^4.52.5
    sass: ^1.93.2
    sharp: ^0.34.4
    sortablejs: ^1.15.6
    start-server-and-test: ^2.1.2
    stylelint: ^16.25.0
    stylelint-config-recommended-scss: ^16.0.2
    stylelint-config-recommended-vue: ^1.6.1
    stylelint-order: ^7.0.0
    stylelint-scss: ^6.12.1
    tailwindcss: ^4.1.14
    tsx: ^4.20.6
    typescript: ^5.9.3
    typescript-eslint: ^8.46.1
    unplugin-dts: 1.0.0-beta.6
    uuid: ^13.0.0
    vite: ^7.1.11
    vite-node: ^3.2.4
    vite-plugin-conditional-compiler: ^0.3.1
    vite-plugin-pwa: ^1.1.0
    vite-plugin-static-copy: ^3.1.4
    vite-plugin-vue-devtools: ^8.0.3
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.2.4
    vue: ^3.5.22
    vue-chartjs: ^5.3.2
    vue-i18n: ^11.1.12
    vue-router: ^4.6.3
    vue-tsc: ^3.1.1
    vue3-social-sharing: ^1.4.1
    vuex: ^4.1.0
    workbox-cacheable-response: ^7.3.0
    workbox-core: ^7.3.0
    workbox-expiration: ^7.3.0
    workbox-precaching: ^7.3.0
    workbox-routing: ^7.3.0
    workbox-strategies: ^7.3.0
    workbox-window: ^7.3.0
    write-yaml-file: ^5.0.0
    yaml: ^2.8.1
    yargs: ^18.0.0
