
export enum LayerStoreActions {
    SetBackground = 'setBackground',
    SetPreviewYear = 'setPreviewYear',
    SetTimedLayerCurrentYear = 'setTimedLayerCurrentYear',
    SetLayerConfig = 'setLayerConfig',
    AddLayer = 'addLayer',
    SetLayers = 'setLayers',
    RemoveLayer = 'removeLayer',
    UpdateLayer = 'updateLayer',
    UpdateLayers = 'updateLayers',
    ClearLayers = 'clearLayers',
    ToggleLayerVisibility = 'toggleLayerVisibility',
    SetLayerVisibility = 'setLayerVisibility',
    SetLayerOpacity = 'setLayerOpacity',
    SetTimedLayerCurrentTimeEntry = 'setTimedLayerCurrentTimeEntry',
    MoveActiveLayerToIndex = 'moveActiveLayerToIndex',
    SetPreviewLayer = 'setPreviewLayer',
    ClearPreviewLayer = 'clearPreviewLayer',
    AddLayerError = 'addLayerError',
    RemoveLayerError = 'removeLayerError',
    SetKmlGpxLayerData = 'setKmlGpxLayerData',
    AddSystemLayer = 'addSystemLayer',
    UpdateSystemLayer = 'updateSystemLayer',
    RemoveSystemLayer = 'removeSystemLayer',
    LoadLayersConfig = 'loadLayersConfig',
}

export enum MapStoreActions {
    Click = 'click',
    ClearClick = 'clearClick',
    SetPinnedLocation = 'setPinnedLocation',
    SetPreviewedPinnedLocation = 'setPreviewedPinnedLocation',
    ClearPreviewPinnedLocation = 'clearPreviewPinnedLocation',
    ClearLocationPopupCoordinates = 'clearLocationPopupCoordinates',
    SetLocationPopupCoordinates = 'setLocationPopupCoordinates',
    SetPrintMode = 'setPrintMode',
    SetRectangleSelectionExtent = 'setRectangleSelectionExtent',
}

export enum PositionStoreActions {
    SetDisplayedFormat = 'setDisplayedFormat',
    SetZoom = 'setZoom',
    IncreaseZoom = 'increaseZoom',
    DecreaseZoom = 'decreaseZoom',
    ZoomToExtent = 'zoomToExtent',
    SetRotation = 'setRotation',
    SetAutoRotation = 'setAutoRotation',
    SetHasOrientation = 'setHasOrientation',
    SetCenter = 'setCenter',
    SetCrossHair = 'setCrossHair',
    SetCameraPosition = 'setCameraPosition',
    SetProjection = 'setProjection',
}

export enum ProfileStoreActions {
    SetCurrentFeatureSegmentIndex = 'setCurrentFeatureSegmentIndex',
    SetProfileFeature = 'setProfileFeature',
}

export enum UIStoreActions {
    SetSize = 'setSize',
    ToggleMenu = 'toggleMenu',
    CloseMenu = 'closeMenu',
    ToggleFullscreenMode = 'toggleFullscreenMode',
    SetEmbed = 'setEmbed',
    SetNoSimpleZoomEmbed = 'setNoSimpleZoomEmbed',
    SetShowLoadingBar = 'setShowLoadingBar',
    SetLoadingBarRequester = 'setLoadingBarRequester',
    ClearLoadingBarRequester = 'clearLoadingBarRequester',
    SetUiMode = 'setUiMode',
    ToggleImportCatalogue = 'toggleImportCatalogue',
    ToggleImportFile = 'toggleImportFile',
    SetHeaderHeight = 'setHeaderHeight',
    SetCompareRatio = 'setCompareRatio',
    SetCompareSliderActive = 'setCompareSliderActive',
    SetFeatureInfoPosition = 'setFeatureInfoPosition',
    SetTimeSliderActive = 'setTimeSliderActive',
    SetShowDisclaimer = 'setShowDisclaimer',
    AddErrors = 'addErrors',
    RemoveError = 'removeError',
    AddWarnings = 'addWarnings',
    RemoveWarning = 'removeWarning',
    SetShowDragAndDropOverlay = 'setShowDragAndDropOverlay',
    SetHideEmbedUI = 'setHideEmbedUI',
    SetForceNoDevSiteWarning = 'setForceNoDevSiteWarning',
}
