import type { GeoAdminLayer, KMLLayer, Layer } from '@swissgeo/layers'
import type { Interval } from 'luxon'

export interface LayerActionFilter {
    /** Base URL of the layer(s) to retrieve. If undefined, accepts all */
    baseUrl?: string
    /** If the layer must be external, not, or both (undefined) */
    isExternal?: boolean
}

export interface LayersStoreState {
    /** Current background layer ID */
    currentBackgroundLayerId: string | undefined
    /**
     * Currently active layers (that have been selected by the user from the search bar or the layer
     * tree)
     *
     * Layers are ordered from bottom to top (last layer is shown on top of all the others)
     */
    activeLayers: Layer[]
    /** All layers' config available to this app */
    config: GeoAdminLayer[]
    /**
     * A layer to show on the map when hovering a layer (catalog and search) but not in the list of
     * active layers.
     */
    previewLayer: Layer | undefined
    /**
     * Interval being picked by the time slider. When set to a valid interval, each active layer
     * with multiple time entries will be looked up for matching time entry. Their current time
     * entry will be set accordingly (or set to undefined if no matching time entry is found)
     */
    previewInterval: Interval | undefined
    /**
     * System layers. List of system layers that are added on top and cannot be directly controlled
     * by the user.
     */
    systemLayers: Layer[]

    previewYear?: number
}

export interface LayersStoreGetters {
    /**
     * Get the current KML layer selected for drawing.
     *
     * That is the KML layer that will be used when the drawing mode is opened.
     *
     * When no KML layer is in active layers, undefined is returned.
     */
    activeKmlLayer(): KMLLayer | undefined
    /**
     * All layers in the config that have the flag `background` to `true` (that can be shown as a
     * background layer).
     */
    backgroundLayers(): GeoAdminLayer[]
    currentBackgroundLayer(): Layer | undefined
    getActiveLayerByIndex(): (index: number) => Layer | undefined
    /**
     * Get index of the active layer by ID.
     *
     * When there exists no layer with this ID then -1 is returned.
     */
    getActiveLayersById(): (layerId: string, options?: LayerActionFilter) => Layer[]
    getIndexOfActiveLayerById(): (layerId: string) => number
    /** Retrieves a layer config metadata defined by its unique ID */
    getLayerConfigById(): (layerId: string) => GeoAdminLayer | undefined
    /**
     * Retrieves layer(s) by ID, isExternal, and baseUrl properties.
     *
     * Search in the active layers and in the preview layer
     *
     * @returns All active layers matching the search params
     */
    getLayersById(): (layerId: string, options?: LayerActionFilter) => Layer[]
    /** Returns true if any layer has been imported from a local file. */
    hasAnyLocalFile(): boolean
    /**
     * Returns true if the layer comes from a third party (external layer or KML layer).
     *
     * KML layers are treated as external when they are generated by another user (no adminId).
     */
    hasDataDisclaimer(): (layerId: string, options?: LayerActionFilter) => boolean
    /** Returns true if the content of the layer has been imported from a local file. */
    isLocalFile(): (layer?: Layer) => boolean
    oldestYear(): number
    /**
     * Return the visible layer on top
     *
     * @returns The top visible layer or undefined if no layers are visible
     */
    visibleLayerOnTop(): Layer | undefined
    /**
     * Filter all the active layers and gives only those who are visible on the map.
     *
     * This includes system layers and the preview layer. The time enabled layer with invalid year
     * are filtered out.
     *
     * Layers are ordered from bottom to top (last layer is shown on top of all the others)
     *
     * @returns All layers that are currently visible on the map
     */
    visibleLayers(): Layer[]
    /** Get visibleLayers with time config. (Preview layers and system layers are filtered) */
    visibleLayersWithTimeConfig(): Layer[]
    youngestYear(): number
}

export type LayersStoreComputedGetters = {
    [Getter in keyof LayersStoreGetters]: ReturnType<LayersStoreGetters[Getter]>
}

export type LayersStore = ReturnType<typeof import('@/store/modules/layers').default>
