<script setup>
import ScaleLine from 'ol/control/ScaleLine'
import { computed, inject, onBeforeUnmount, onMounted, ref } from 'vue'
import { useStore } from 'vuex'

import { LV95 } from '@/utils/coordinates/coordinateSystems'

const scaleLineElement = ref(null)

const store = useStore()
const zoom = computed(() => store.state.position.zoom)
const projection = computed(() => store.state.position.projection)

const showScaleLine = computed(() => projection.value.epsg === LV95.epsg || zoom.value >= 9)

const scaleLine = new ScaleLine({
    className: 'scale-line',
})

const olMap = inject('olMap')
onMounted(() => {
    scaleLine.setTarget(scaleLineElement.value)
    olMap.addControl(scaleLine)
})
onBeforeUnmount(() => olMap.removeControl(scaleLine))
</script>

<template>
    <!-- The initialization will fail with `v-if` if initial zoom is too low. -->
    <div v-show="showScaleLine" ref="scaleLineElement" data-cy="scaleline" />
</template>

<style lang="scss">
/* Must be unscoped, as the scaleLine is generated by OpenLayers on the fly */
@import '@/scss/webmapviewer-bootstrap-theme';

.scale-line {
    width: 150px;

    &-inner {
        max-width: 100%;
        border: 2px solid $black;
        border-top: none;
        text-align: center;
        font-weight: bold;
        color: $black;
        background-color: rgba($white, 0.7);
    }
}
</style>
