<template>
    <!-- The initialization will fail with `v-if` if initial zoom is too low. -->
    <div v-show="showScaleLine" ref="scaleLine" data-cy="scaleline" />
</template>

<script>
import { LV95 } from '@/utils/coordinates/coordinateSystems'
import ScaleLine from 'ol/control/ScaleLine'
import { mapState } from 'vuex'

export default {
    inject: ['getMap'],
    computed: {
        ...mapState({
            currentZoom: (state) => state.position.zoom,
            projection: (state) => state.position.projection,
        }),
        showScaleLine() {
            return this.projection.epsg === LV95.epsg || this.currentZoom >= 9
        },
    },
    created() {
        this.scaleLine = new ScaleLine({
            className: 'scale-line',
        })
    },
    mounted() {
        this.scaleLine.setTarget(this.$refs.scaleLine)
        this.getMap().addControl(this.scaleLine)
    },
    unmounted() {
        this.getMap().removeControl(this.scaleLine)
    },
}
</script>

<style lang="scss">
/* Must be unscoped, as the scaleLine is generated by OpenLayers on the fly */
@import 'src/scss/webmapviewer-bootstrap-theme';

.scale-line {
    width: 150px;

    &-inner {
        max-width: 100%;
        border: 2px solid $black;
        border-top: none;
        text-align: center;
        font-weight: bold;
        color: $black;
        background-color: rgba($white, 0.7);
    }
}
</style>
