name: Create test link on PR creation
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create/update test link on DEV
        if: ${{ github.base_ref == 'develop' }}
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '.+'
          body-template: |

            [Test link](https://sys-map.dev.bgdi.ch/%headbranch%/index.html)
          body-update-action: 'suffix'
          body-uppercase-head-match: false

      - name: Create/update deployment link on INT
        if: ${{ github.base_ref == 'master' }}
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '.+'
          body-template: |

            [Test link](https://sys-map.int.bgdi.ch/)
          body-update-action: 'suffix'
          body-uppercase-head-match: false
